### ISSUE TITLE
Container spun up unnecessarily when using Oracle Cloud ATP

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-test-resources#104]
### Expected Behavior

When configuring Oracle Cloud ATP a Oracle Database container should not be spun up.

```yaml
datasources:
  default:
    ocid: ${ATP_OCID}
    walletPassword: ${ATP_WALLET_PASSWORD}
    username: mnocidemo
    password: ${ATP_USER_PASSWORD}
```

### Actual Behaviour

A database container containing Oracle is started although it is not used.

### Steps To Reproduce

Follow the guide https://guides.micronaut.io/latest/micronaut-oracle-autonomous-db-gradle-java.html

### Version

3.7.1
