### ISSUE TITLE
Does not run on GitLab CI docker runner

### ISSUE THREAD

**Issue by fhoner** [micronaut-projects/micronaut-test-resources#119]
### Issue description

When running tests locally, everything works as expected: A mongodb container is started and mongodb connection is configured automatically to something like that: `mongodb://localhost:58940` (where 58940 is a random port)  
However running the same build on our GitLab CI runner fails since `localhost` won't reach the mongodb container. Actually, it should connect to something like this: `mongodb://docker:27017`
Is there a way to set the hostname somehow?

```
image: gradle:jdk11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - nativeTest

services:
  - name: docker:dind
    command: [ "--tls=false" ]

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:
    - ./gradlew build

nativeTest:
  stage: nativeTest
  image:
    name: ghcr.io/graalvm/native-image:java11
    entrypoint:
      - ""
  script:
    - ./gradlew graalvmTestNativeImage
```

```
test-resources:
  containers:
    mongodb:
      image-name: mongo:4
```  

Edit: Problem solved. Actually, it already connected to `docker` host, but switched during the build to `localhost`. There was a file called `application-cloud.yml` which was - by whatever reason - taken into account during the tests. Renaming it to `application-prod.yml` solved it, build is running now.
