### ISSUE TITLE
test-resources, PostgreSQL and kotest

### ISSUE THREAD

**Issue by mf-guse** [micronaut-projects/micronaut-test-resources#120]
### Expected Behavior

When creating a Test annotated with io.micronaut.test.extensions.kotest5.annotation.MicronautTest and having something like

```
datasources:
  default:
    db-type: postgresql
    dialect: PostgreSQL10Dialect
    schema-generate: create_drop

test-resources:
  containers:
    postgres:
      image-name: postgres:11

```
in application-test.yaml

I expect micronaut-test-resources to start a PostgreSQL Testcontainer.

### Actual Behaviour

The settings in application-test.yaml are ignored, no Testcontainer ist started and some H2 stuff is used.

### Steps To Reproduce

Run example application test from IntelliJ using the kotest plugin.

### Environment Information

- Windows 10
- Java 17
- id "io.micronaut.test-resources" version "3.6.3"
- Docker provided by Rancher Desktop
- Ubuntu WSL2

### Example Application

[https://github.com/mf-guse/micronaut-test-resources-test](https://github.com/mf-guse/micronaut-test-resources-test)

### Version

3.7.3
