### ISSUE TITLE
Add support for Wait Strategies for generic containers

### ISSUE THREAD

**Issue by heineson** [micronaut-projects/micronaut-test-resources#123]
### Feature description

It would be very useful to have support for customizing the criteria for when a generic container is ready for use, like documented here: https://www.testcontainers.org/features/startup_and_waits/

An example would be something like this in `application.yml`

```
test-resources:
  containers:
    custom-container:
      image-name: my-image
      hostnames:
        - my.host
      exposed-ports:
        - my.port: 9876
      wait-strategy:
        - log-message: ".*Ready to accept connections.*\\n"
```
