### ISSUE TITLE
Enable container dependencies through configuration

### ISSUE THREAD

**Issue by saw303** [micronaut-projects/micronaut-test-resources#147]
### Feature description

In some circumstances containers have dependencies. For example one container is depending on a database container. According to the Testcontainers [documentation](https://www.testcontainers.org/features/startup_and_waits/#depending-on-another-container) they do provide support for that by

```java
GenericContainer<?> redis = new GenericContainer<>("redis:3.0.2").withExposedPorts(6379);

GenericContainer<?> nginx = new GenericContainer<>("nginx:1.9.4")
                                .dependsOn(redis)
                                .withExposedPorts(80);
```

maybe it could be something like this in the `application.yml`.

```yml
test-resources:
  containers:
    
    product-engine:
      image-name: ghcr.io/abc/product-engine:0.1.15
      hostnames:
        - product.engine.host
      exposed-ports:
        - product.engine.port: 8080
      env:
        - DB_HOST: "pedb"
      network: productnet # same network, so they can talk to each other
      depends-on:  # <-- That's the new feature. Declaring dependencies
        - product-engine-db

    product-engine-db:
      image-name: ghcr.io/abc/productdb:1.0.0-demo
      network: productnet # same network, so they can talk to each other
      network-aliases: pedb # a hostname, so product-engine can talk to the db using the name.
```

depends on will configure a dependency on the container `container.dependsOn()`.
