### ISSUE TITLE
Add support for custom networks

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-test-resources#31]
### Feature description

Advanced test containers support may require to add support for custom networks. We could allow configuring networks by convention, for example:

```yaml
test-resources:
    container-networks:
         - shared-network
    containers:
          foo:
             network: shared-network
          bar:
             network: shared-network
````
