### ISSUE TITLE
Two datasources reuse the same mysql container

### ISSUE THREAD

**Issue by JesusMetapack** [micronaut-projects/micronaut-test-resources#371]
### Feature description

We have this configuration
`
test-resources:
  containers:
    mysql:
      image-name: mysql:8
      db-name: cost-engine
      username: cost-engine
      password: test # According to test containers documentation this is used as the password for the root user also

datasources: # URL will be inserted by Micronaut test resources
  read:
    db-type: mysql
  write:
    db-type: mysql
`

The test resource resolver injects the properties url, username and password correctly to both datasources, but our repository classes should be able to use the read and the write datasource pointing to the same container 
The reason is that in real life, our mysql database has two urls, one for reads and one for writes, but they both use the same physical database

Unfortunately there is no way to tell micronaut to do that when using test resources
`
io.micronaut.testresources.testcontainers.TestContainers.getOrCreate(...) 
`
uses a map, to detect if it needs to inject a new container to resolve a resource property, like url, but the map key is in that case, based on each datasource property, i.e datasource.read.db-type,  and datasource.write.db-type, so because of that, it just spins a new container

Would be good to be able to tell the resolver, that we want both datasources to just use the same url

Is there a way to achieve this currently, without programmatically having to manually do that in every integration test ?

**Comment by JesusMetapack** [comment]
Can I request this new configuration?
```
test-resources:
  containers:
    mysql:
      image-name: mysql:8
      db-name: cost-engine
      username: cost-engine
      password: test # According to test containers documentation this is used as the password for the root user also

datasources: # URL will be inserted by micronaut test resources
  read:
    db-type: mysql
    db-name: cost-engine
    dialect: MYSQL
    username: cost-engine
    password: test
  write:
    db-type: mysql
    db-name: cost-engine
    dialect: MYSQL
    username: cost-engine
    password: test
```

So the db-name is used to identify the container and no more containers are created?
