### ISSUE TITLE
Custom environment and rw-fs-bind not passed to the container

### ISSUE THREAD

**Issue by simper66** [micronaut-projects/micronaut-test-resources#52]
### Expected Behavior

The custom config in the yaml should be passed to the container

### Actual Behaviour

Given this yaml

```yaml
test-resources:
  containers:
    postgres:
      image-name: postgres:14-alpine
      rw-fs-bind:
        "/docker/var/pg14_alpine_tests": "/var/lib/postgresql/data"
      env:
        POSTGRES_USER: nrt_platform_editor
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: nrt_platform_editor
```

**DOCKER INSPECT XXXXXXXX**

```json
........
   "Mounts": [
            {
                "Type": "volume",
                "Name": "2da16a2e67adbbad2bfe7c93e9589c246708cd4e0f71d3273cd33c6e4447d437",
                "Source": **"/var/lib/docker/volumes/2da16a2e67adbbad2bfe7c93e9589c246708cd4e0f71d3273cd33c6e4447d437/_data",
                "Destination": "/var/lib/postgresql/data",**
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
.......
"Env": [
                **"POSTGRES_USER=test",
                "POSTGRES_PASSWORD=test",
                "POSTGRES_DB=test",**
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.utf8",
                "PG_MAJOR=14",
                "PG_VERSION=14.4",
                "PG_SHA256=c23b6237c5231c791511bdc79098617d6852e9e3bdf360efd8b5d15a1a3d8f6a",
                "PGDATA=/var/lib/postgresql/data"
            ],
```

One curious thing

If i write:

```yaml
 rw-fs-bind:
        - /docker/var/pg14_alpine_tests: /var/lib/postgresql/data
```

instead of 

```yaml
   rw-fs-bind:
        /docker/var/pg14_alpine_tests: /var/lib/postgresql/data
```

It works;

```json
 "Mounts": [
            {
                "Type": "bind",
                "Source": "/docker/var/pg14_alpine_tests",
                "Destination": "/var/lib/postgresql/data",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

### Environment Information

JAVA 19
SPOCK2
id 'io.micronaut.application' version '3.5.0'
id 'io.micronaut.test-resources' version '3.5.0'

### Version

3.5.3

**Comment by melix** [comment]
Isn't it an error in the YAML syntax? For a single entry, you should either have:

```yaml
test-resources:
  containers:
    postgres:
      image-name: postgres:14-alpine
      rw-fs-bind:  "/docker/var/pg14_alpine_tests": "/var/lib/postgresql/data"
      env:
        POSTGRES_USER: nrt_platform_editor
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: nrt_platform_editor
```

or

```yaml
test-resources:
  containers:
    postgres:
      image-name: postgres:14-alpine
      rw-fs-bind:
        - "/docker/var/pg14_alpine_tests": "/var/lib/postgresql/data"
      env:
        POSTGRES_USER: nrt_platform_editor
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: nrt_platform_editor
```

**Comment by simper66** [comment]
I have tried any permutation (lists, maps, quotes, no quotes, etc)

rw-fs-bind does strange thing

env never works

nervermind, perhaps is a groovy problem...

**Comment by melix** [comment]
Actually I made a mistake, you need to put each entry on a separate line (my IDE complains if I don't):

```yaml
test-resources:
  containers:
    postgres:
      image-name: postgres:14-alpine
      rw-fs-bind:
        - "/docker/var/pg14_alpine_tests": "/var/lib/postgresql/data"
      env:
        - POSTGRES_USER: nrt_platform_editor
        - POSTGRES_PASSWORD: 1234
        - POSTGRES_DB: nrt_platform_editor
```

Yaml...
