### ISSUE TITLE
R2DBC with Flyway creating multiple Postgres containers

### ISSUE THREAD

**Issue by zsiegel** [micronaut-projects/micronaut-test-resources#521]
### Expected Behavior

When using Flyway, R2DBC, and JDBC there should be one postgres container started that is migrated. This appears to be similar to #65 

### Actual Behaviour

Multiple postgres containers are started. The application and tests still run but there should only be one container.

### Steps To Reproduce

Utilizing the following configuration with BOM `4.3.2` on a Gradle + Kotlin project.

```yml
test-resources:
  containers:
    postgres:
      image-name: postgres:15-alpine

flyway:
  datasources:
    default:
      dialect: postgres
      enabled: true

datasources:
  default:
    dialect: postgres

r2dbc:
  datasources:
    default:
      dialect: postgres
```

### Environment Information

- MacOS
- Micronaut BOM 4.3.2
- Gradle

### Version

4.3.2
