### ISSUE TITLE
Support JDBC's container `initScriptPath` property

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-test-resources#81]
### Feature description

```yml
test-resources:
  containers:
    mariadb:
      image-name: mariadb:10.3
      init-script-path: ./my.sql
```
I see we always use the defaults: username, passwords etc. maybe it would be nice to allow to change them.
