### ISSUE TITLE
Misaligned yaml configuration example in docs

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-test-resources#82]
### Actual Behaviour

`env` and `labels` are incorrectly aligned.
```yaml
test-resources:
  containers:
    mycontainer:
      image-name: my/container
      hostnames:
        - my.service.host
      exposed-ports:
        - my.service.port: 1883
      command: "some.sh"
        env:
          - MY_ENV_VAR: "my value"
        labels:
          - my.label: "my value"
      startup-timeout: 120s
```

### Version

latest
